// data.js
export default [
  {
    title: "ChatGPT",
    subtitle: "AI-powered Conversational Assistant",
    features: ["Conversational AI", "Custom Instructions", "Code Interpreter"],
    differentiators: [
      "GPT-4 model",
      "Wide-ranging API support",
      "Multi-turn dialogue",
    ],
    clients: ["OpenAI API Users", "Businesses", "Educational Institutions"],
    industries: ["Education", "Customer Service", "Technology"],
    pricing: "Free with Pro options starting at $20/month",
    imageUrl: "https://chat.openai.com/favicon.ico",
    link: "https://chat.openai.com/",
    slug: "chatgpt",
  },
  {
    title: "Google Gemini",
    subtitle: "Generative AI for Google Workspace & Search",
    features: ["Text Generation", "Translation", "Search Assistance"],
    differentiators: [
      "Integrated into Google products",
      "Bard assistant capabilities",
      "Multimodal inputs",
    ],
    clients: ["Google Workspace Users", "Healthcare", "Finance"],
    industries: ["Productivity", "Search", "Healthcare"],
    pricing: "Usage-based API pricing",
    imageUrl: "https://bard.google.com/favicon.ico",
    link: "https://bard.google.com/",
    slug: "goodle-gemini",
  },
  {
    title: "GitHub Copilot · Your AI pair programmer",
    subtitle: "GitHub web page CSS styles and font loading",
    features: [
      "Dynamic theme switching",
      "Preloading assets for performance optimization",
    ],
    differentiators: [
      "Support for dark and light theme",
      "Accessibility features like animated images and link underlines",
    ],
    clients: ["Shopify", "honeywell"],
    industries: ["Web development", "Software development"],
    pricing: "N/A",
    description:
      "GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 420 million projects.",
    imageUrl: "https://github.githubassets.com/favicons/favicon.svg",
    link: "https://github.com/features/copilot",
    slug: "github-com-features-copilot",
  },
  {
    title: "Claude",
    subtitle: "Conversational AI Assistant by Anthropic",
    features: [
      "Dialogue Interaction",
      "Multi-turn Conversations",
      "Context Retention",
    ],
    differentiators: [
      "Focus on safety",
      "Context length up to 100K tokens",
      "Ethical AI principles",
    ],
    clients: ["Businesses", "Educational Institutions", "Non-profits"],
    industries: ["Customer Support", "Education", "Healthcare"],
    pricing: "Contact for pricing",
    imageUrl: "https://www.anthropic.com/favicon.ico",
    link: "https://www.anthropic.com/claude",
    slug: "claude",
  },
  {
    title: "Jasper AI",
    subtitle: "AI Content and Copywriting Assistant",
    features: ["Content Generation", "SEO Optimization", "Custom Brand Voice"],
    differentiators: [
      "Focus on marketing",
      "Tone and style customization",
      "Integrated SEO tools",
    ],
    clients: ["Marketing Teams", "Content Creators", "E-commerce"],
    industries: ["Marketing", "E-commerce", "Publishing"],
    pricing: "Starting at $39/month",
    imageUrl: "https://www.jasper.ai/favicon.ico",
    link: "https://www.jasper.ai/",
    slug: "jasper-ai",
  },
  {
    title: "Cohere",
    subtitle: "LLM APIs for Text Generation and Search",
    features: ["Text Generation", "Search", "Semantic Understanding"],
    differentiators: [
      "Multilingual support",
      "Optimized for enterprises",
      "Specialized APIs for search",
    ],
    clients: ["Enterprises", "Developers", "Startups"],
    industries: ["Customer Support", "Healthcare", "Retail"],
    pricing: "Contact for enterprise pricing",
    imageUrl: "https://cohere.ai/favicon.ico",
    link: "https://cohere.ai/",
    slug: "cohere",
  },
  {
    title: "LLaMA",
    subtitle: "Meta’s Large Language Model",
    features: ["Natural Language Processing", "Open-source", "Customizable"],
    differentiators: [
      "Open-source and community-driven",
      "Research-oriented",
      "High efficiency",
    ],
    clients: ["Researchers", "Developers", "Academia"],
    industries: ["Research", "Technology", "Education"],
    pricing: "Open-source (Free)",
    imageUrl: "https://ai.meta.com/favicon.ico",
    link: "https://ai.meta.com/llama/",
    slug: "llama",
  },
  {
    title: "Mistral",
    subtitle: "Open-weight LLM by Mistral AI",
    features: [
      "Open-weight model",
      "Research-ready",
      "Efficient NLP capabilities",
    ],
    differentiators: [
      "Highly efficient",
      "100% open-weight",
      "Compatible with existing NLP tasks",
    ],
    clients: ["Developers", "Academic Researchers", "Startups"],
    industries: ["Research", "Education", "Software Development"],
    pricing: "Open-source (Free)",
    imageUrl: "https://mistral.ai/favicon.ico",
    link: "https://mistral.ai/",
    slug: "mistral",
  },
  {
    title: "Writer AI",
    subtitle: "AI Writing and Content Platform",
    features: [
      "Content Generation",
      "Grammar & Style Checks",
      "SEO Optimization",
    ],
    differentiators: [
      "Tailored for brand voice",
      "Specialized for marketing",
      "SEO integrations",
    ],
    clients: ["Marketing Agencies", "Content Teams", "E-commerce"],
    industries: ["Marketing", "Publishing", "Technology"],
    pricing: "Starting at $18/month",
    imageUrl: "https://writer.com/favicon.ico",
    link: "https://writer.com/",
    slug: "writer-ai",
  },
  {
    title: "ALEPH Alpha",
    subtitle: "German AI Company’s Multimodal AI",
    features: ["Multimodal Input", "Translation", "Text Analysis"],
    differentiators: [
      "Focused on European data",
      "GDPR compliant",
      "Multilingual capabilities",
    ],
    clients: ["European Enterprises", "Government", "Healthcare"],
    industries: ["Government", "Healthcare", "Education"],
    pricing: "Contact for pricing",
    imageUrl: "https://www.aleph-alpha.com/favicon.ico",
    link: "https://www.aleph-alpha.com/",
    slug: "aleph-alpha",
  },
];
